Migrate to github actions

diff --git a/mkimage b/mkimage
--- a/mkimage
+++ b/mkimage
@@ -7,7 +7,8 @@ ROOT=$(cd "$(dirname "$0")" && pwd)
 
 TARGET=${1:?Specify the target filename}
 DIST=${2:-stable}
-SNAPSHOT_ID=${3:-}
+PLATFORM=${3:-$(dpkg --print-architecture)}
+SNAPSHOT_ID=${4:-}
 
 LOGFILE=${TARGET}.log
 
@@ -26,6 +27,10 @@ if [ -f "${ROOT}/keys/${DIST}.gpg" ]; then
     gpg --no-default-keyring --keyring "$KEYRING" --import "${ROOT}/keys/${DIST}.gpg"
 fi
 
+use_qemu_static() {
+    [[ "$PLATFORM" == "arm64" ]]
+}
+
 export DEBIAN_FRONTEND=noninteractive
 
 DIRS_TO_TRIM="/usr/share/man
@@ -36,10 +41,39 @@ DIRS_TO_TRIM="/usr/share/man
 /usr/share/info
 "
 
+debootstrap_arch_args=( )
+
+if use_qemu_static ; then
+    debootstrap_arch_args+=( --arch "$PLATFORM" )
+fi
+
 rootfsDir=$(mktemp -d)
 echo "Building base in $rootfsDir"
-DEBOOTSTRAP_DIR="$DEBOOTSTRAP_DIR" debootstrap --keyring "$KEYRING" --variant container --foreign "${DIST}" "$rootfsDir"
-chroot "$rootfsDir" bash debootstrap/debootstrap --second-stage
+DEBOOTSTRAP_DIR="$DEBOOTSTRAP_DIR" debootstrap "${debootstrap_arch_args[@]}"  --keyring "$KEYRING" --variant container --foreign "${DIST}" "$rootfsDir"
+
+# get path to "chroot" in our current PATH
+chrootPath="$(type -P chroot)"
+rootfs_chroot() {
+    # "chroot" doesn't set PATH, so we need to set it explicitly to something our new debootstrap chroot can use appropriately!
+    # set PATH and chroot away!
+    PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
+            "$chrootPath" "$rootfsDir" "$@"
+
+}
+
+if use_qemu_static ; then
+    echo "Setting up qemu static in chroot"
+    usr_bin_modification_time=$(stat -c %y "$rootfsDir"/usr/bin)
+    if [ -f "/usr/bin/qemu-aarch64-static" ]; then
+        find /usr/bin/ -type f -name 'qemu-*-static' -exec cp {} "$rootfsDir"/usr/bin/. \;
+    else
+        echo "Cannot find aarch64 qemu static. Aborting..." >&2
+        exit 1
+    fi
+    touch -d "$usr_bin_modification_time" "$rootfsDir"/usr/bin
+fi
+
+rootfs_chroot bash debootstrap/debootstrap --second-stage
 
 repo_url="http://deb.debian.org/debian"
 sec_repo_url="http://security.debian.org/"
@@ -54,10 +88,10 @@ if [ "$DIST" != "unstable" ]; then
     echo "deb ${sec_repo_url} $DIST/updates main" >> "$rootfsDir/etc/apt/sources.list"
 fi
 
-chroot "$rootfsDir" apt-get update
-chroot "$rootfsDir" apt-get upgrade -y -o Dpkg::Options::="--force-confdef"
+rootfs_chroot apt-get update
+rootfs_chroot apt-get upgrade -y -o Dpkg::Options::="--force-confdef"
 
-chroot "$rootfsDir" dpkg -l | tee "$TARGET.manifest"
+rootfs_chroot dpkg -l | tee "$TARGET.manifest"
 
 echo "Applying docker-specific tweaks"
 # These are copied from the docker contrib/mkimage/debootstrap script.
@@ -67,15 +101,6 @@ echo "Applying docker-specific tweaks"
 #     interested in building versions that this guard would apply to,
 #     so simply apply the tweak unconditionally.
 
-# get path to "chroot" in our current PATH
-chrootPath="$(type -P chroot)"
-rootfs_chroot() {
-    # "chroot" doesn't set PATH, so we need to set it explicitly to something our new debootstrap chroot can use appropriately!
-    # set PATH and chroot away!
-    PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
-            "$chrootPath" "$rootfsDir" "$@"
-
-}
 
 # prevent init scripts from running during install/update
 echo >&2 "+ echo exit 101 > '$rootfsDir/usr/sbin/policy-rc.d'"
@@ -221,7 +246,16 @@ echo "host" > "$rootfsDir/etc/hostname"
 # Capture the most recent date that a package in the image was changed.
 # We don't care about the particular date, or which package it comes from,
 # we just need a date that isn't very far in the past.
+
+# We get multiple errors like:
+# gzip: stdout: Broken pipe
+# dpkg-parsechangelog: error: gunzip gave error exit status 1
+#
+# TODO: Why?
+set +o pipefail
 BUILD_DATE="$(find "$rootfsDir/usr/share/doc" -name changelog.Debian.gz -print0 | xargs -0 -n1 -I{} dpkg-parsechangelog -SDate -l'{}' | xargs -l -i date --date="{}" +%s | sort -n | tail -n 1)"
+set -o pipefail
+
 
 echo "Trimming down"
 for DIR in $DIRS_TO_TRIM; do
@@ -251,6 +285,13 @@ chroot "$rootfsDir" dpkg-query -W -f '${Package} ${Installed-Size}\n'
 echo "Largest dirs"
 du "$rootfsDir" | sort -n | tail -n 20
 echo "Built in $rootfsDir"
+
+if use_qemu_static ; then
+    echo "Cleaning up qemu static files from image"
+    usr_bin_modification_time=$(stat -c %y "$rootfsDir"/usr/bin)
+    rm -rf "$rootfsDir"/usr/bin/qemu-*-static
+    touch -d "$usr_bin_modification_time" "$rootfsDir"/usr/bin
+fi
 
 tar cf "$TARGET" -C "$rootfsDir" .
 rm -r "$rootfsDir"
